### PR TITLE
Navbar, footer, fonts

### PR DESCRIPTION
**Pull request by joshuazhu17**
Put the navbar and footer on the left and right sides, respectively. Added IBM Plex Mono font to the website.

TO DO:
Style the navbar like in the Figma
Style the footer like in the Figma

### CODE REVIEW

**Comment by zhangjuliet** [comment]
Looks good so far! Can you also style the Navbar so that the link to the current/active page is highlighted?

**Comment by bliutech** [comment]
@zhangjuliet going to merge for now instead. I don't think we need to implement that JavaScript at the moment to handling that styling just to get the general feel.

**Review by bliutech — CHANGES_REQUESTED** [review]
Please remove all of these font files. Not necessary. Just link the font instead.

**Review by bliutech — APPROVED** [review]
LGTM.

**Pull request merged**
