### PR TITLE
Implement basic animated splash screen

### LINKED ISSUE #12: Add Splash Screen
- [ ] reference Figma to implement loading page. https://www.figma.com/file/m9sfSZsTvvUwLczBbxYLNo/PBR-Team-Site?node-id=0%3A1&t=toCxXkHwDwIl8NxG-1
- [x] Implement first basic layout using SCSS and then add animation

### PR DESCRIPTION
**Pull request by zhangjuliet**
Addresses #12 
A little different from the Figma, but I wanted to push a basic animated splash screen that we can experiment with:

https://user-images.githubusercontent.com/65837446/210012201-f4149640-2fc5-43e0-baba-b50cfcb73e7f.mov

**TODO**
* One issue with this implementation is that for really narrow screens, the font becomes too small to read and I didn't write that many lines of output so some of the page is blank. Easily solvable with media queries though.
* We might want to change the content being output to something more creative.

### CODE REVIEW

**Comment by bliutech** [comment]
@zhangjuliet oh hey! That's pretty good. 👀

**Review by bliutech — CHANGES_REQUESTED** [review]
Could we make this slower and also stays on the screen until like a button is clicked to move to the main website? Similar to Project Sekai's splash screen pacing. https://sekai.team/

**Comment by zhangjuliet** [comment]
Yeah I'll make it slower when we redesign later. Project Sekai's automatically moves to Home, though you can skip the animation by clicking the _skip_ button. Should we do that option instead?

**Comment by bliutech** [comment]
Yeah that's a good idea as well. Did you want me to leave this PR open so that we can continue to work on this or should I just merge right away?

**Comment by zhangjuliet** [comment]
Let's leave it open for now, I feel like the splash screen design will change.

**Comment by bliutech** [comment]
Added some fixes and implementation.

**Review by bliutech — APPROVED** [review]
LGTM.

**Pull request merged**
